pool:
 vmImage: window-latest

stages: 
   - stage: Stage1
     jobs:
      - job: Job1

   - stage: stageA
     dependsOn: Stage1
     jobs:
       - job: JobA

   - stage: Stage2
     dependsOn: []
     jobs:
      - job: Job2
       